# These are supported funding model platforms

github: brencon
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# tidelift: # Replace with your Tidelift package name
# custom: # Replace with up to 4 custom sponsorship URLs
