import logging
import re
from typing import Optional

from heal_plz.db.models.incident import Incident
from heal_plz.db.models.resolution import Resolution
from heal_plz.db.models.root_cause import RootCause
from heal_plz.engine.fix_generator import FixResult
from heal_plz.integrations.github.client import GitHubClient

logger = logging.getLogger(__name__)


class PRCreator:
    def __init__(self, github_client: GitHubClient) -> None:
        self.github = github_client

    async def create_pr(
        self,
        owner: str,
        repo: str,
        incident: Incident,
        root_cause: RootCause,
        fix_result: FixResult,
        base_branch: str = "main",
    ) -> Optional[dict]:
        slug = self._slugify(incident.title)
        branch_name = f"heal-plz/{incident.incident_number}-{slug}"

        base_sha = await self.github.get_default_branch_sha(owner, repo)
        if not base_sha:
            logger.error("Could not get base branch SHA")
            return None

        created = await self.github.create_branch(
            owner, repo, branch_name, base_sha
        )
        if not created:
            logger.error("Could not create branch %s", branch_name)
            return None

        for change in fix_result.changes:
            existing = await self.github.get_file_content(
                owner, repo, change.path, ref=base_branch
            )
            success = await self.github.create_or_update_file(
                owner=owner,
                repo=repo,
                path=change.path,
                content=change.content,
                message=f"fix: {incident.title}\n\nIncident: #{incident.incident_number}\nAuto-generated by heal-plz",
                branch=branch_name,
            )
            if not success:
                logger.error("Failed to update file %s", change.path)
                return None

        body = self._build_pr_body(incident, root_cause, fix_result)
        pr = await self.github.create_pull_request(
            owner=owner,
            repo=repo,
            title=f"[heal-plz] Fix: {incident.title}",
            body=body,
            head=branch_name,
            base=base_branch,
        )

        if pr:
            logger.info(
                "Created PR #%s for incident #%d",
                pr.get("number"),
                incident.incident_number,
            )

        return pr

    def _build_pr_body(
        self,
        incident: Incident,
        root_cause: RootCause,
        fix_result: FixResult,
    ) -> str:
        files_changed = ", ".join(
            f"`{c.path}`" for c in fix_result.changes
        )

        return f"""## heal-plz Auto-Fix

**Incident**: #{incident.incident_number} — {incident.title}
**Priority**: {incident.priority.value}
**Root Cause**: {root_cause.category.value}

### Root Cause Analysis
{root_cause.description}

### Changes
{fix_result.description}

**Files changed**: {files_changed}

### Fix Details
- **Model**: {fix_result.model}
- **Attempt**: {fix_result.attempt}
- **Confidence**: {root_cause.confidence_score:.0%}

---
*This PR was automatically generated by [heal-plz](https://github.com/brencon/heal-plz) — the self-healing coding platform.*
"""

    def _slugify(self, text: str) -> str:
        slug = text.lower()
        slug = re.sub(r"[^a-z0-9]+", "-", slug)
        slug = slug.strip("-")
        return slug[:40]
